import { 
  Store, 
  Gift, 
  BarChart3, 
  ShoppingBag, 
  MessageSquare, 
  Users, 
  Settings, 
  Package,
  TrendingUp,
  Eye,
  EyeOff,
  Plus,
  Edit,
  Trash2,
  Search,
  Home,
  Grid3x3,
  Heart,
  ShoppingCart,
  User,
  LogOut,
  Menu,
  X,
  ChevronRight,
  ChevronDown,
  Star,
  Filter,
  Calendar,
  DollarSign,
  Tag,
  HelpCircle,
  Upload,
  Image as ImageIcon,
  Minus,
  Lock
} from 'lucide-react';

export const Icons = {
  store: Store,
  gift: Gift,
  analytics: BarChart3,
  orders: ShoppingBag,
  comments: MessageSquare,
  users: Users,
  settings: Settings,
  package: Package,
  trendingUp: TrendingUp,
  eye: Eye,
  eyeOff: EyeOff,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  search: Search,
  home: Home,
  grid: Grid3x3,
  heart: Heart,
  cart: ShoppingCart,
  user: User,
  logout: LogOut,
  menu: Menu,
  close: X,
  x: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  star: Star,
  filter: Filter,
  calendar: Calendar,
  dollar: DollarSign,
  tag: Tag,
  help: HelpCircle,
  upload: Upload,
  image: ImageIcon,
  minus: Minus,
  lock: Lock,
};

export type IconName = keyof typeof Icons;